datasource: @datasource@
spring:
  datasource:
    druid:
      password: @spring.datasource.password@
      driver-class-name: @spring.datasource.driver-class-name@
      url: @spring.datasource.url@
      username: @spring.datasource.username@
      type: @spring.datasource.type@
      filter:
        config:
          enabled: @sql.encoding.enabled@
      connection-properties: config.decrypt=true;config.decrypt.key=@publicKey@



mybatis:
  mapper-locations: classpath*:sqlmap/*.xml